image: golang:1.19

pipelines:
  branches:
    develop:
      - parallel:
          - step:
              name: Develop - build and deploy
              script:
                - apt-get update && apt-get install -y zip
                - mkdir deploy
                - GOOS=linux GOARCH=amd64 go build -o deploy/rbac cmd/rbac/rbac.go
                - zip -D -j -r deploy/rbac.zip deploy/rbac
                - rm -rf  /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/generated/pipeline/pipes
                - pipe: atlassian/aws-lambda-deploy:1.3.0
                  variables:
                    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                    FUNCTION_NAME: 'd2din-testing-rbac'
                    COMMAND: 'update'
                    ZIP_FILE: 'deploy/rbac.zip'
    main:
      - parallel:
          - step:
              name: Production - build and deploy
              script:
                - apt-get update && apt-get install -y zip
                - mkdir deploy
                - GOOS=linux GOARCH=amd64 go build -o deploy/rbac cmd/rbac/rbac.go
                - zip -D -j -r deploy/rbac.zip deploy/rbac
                - rm -rf  /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/generated/pipeline/pipes
                - pipe: atlassian/aws-lambda-deploy:1.3.0
                  variables:
                    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                    FUNCTION_NAME: 'd2din-production-rbac'
                    COMMAND: 'update'
                    ZIP_FILE: 'deploy/rbac.zip'
